---
name: ğŸ¦„ Code Linting & Scanning


on:
  workflow_dispatch:
  push:


# Limit workflow to one job per branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  code-quality:
    name: ğŸ’„ Code Quality
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“© Checkout the source w/ full depth(for tags and SCM)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: ğŸ Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9


      - name: ğŸŒ± Linting with black
        run: |
          mkdir -p /tmp/artifacts
          make install
          make lint


      - name: ğŸ¦¹â€â™‚ï¸ Scanning with bandit
        run: |
          bandit                                    \
            -v                                      \
            -f txt                                  \
            -r ./storyteller                        \
            -c "pyproject.toml"                     \
            --output /tmp/artifacts/bandit_scan.txt \
          || $( exit 0 ); echo $?


      - name: ğŸ–‹ï¸ mypy Type Checking
        run: |
          mypy                         \
            storyteller                \
            --ignore-missing-imports   \
            --follow-imports=skip      \
            --show-error-codes         \
            --show-column-numbers      \
            --pretty                   \
            > /tmp/artifacts/mypy.txt  \
          || $( exit 0 ); echo $?


      - name: ğŸ“ Archiving Artifacts
        uses: actions/upload-artifact@v3
        if: ${{ !failure() }}
        continue-on-error: true
        with:
          name: scan-artifacts
          retention-days: 1
          path: |
            /tmp/artifacts